### ISSUE TITLE
Problemas na instalação  Class 'Apiki\SEO\REST\Core' not found

### ISSUE THREAD

**Issue by lmaiacosta** [Apiki/wordpress-seo-rest#1]
Dando problema na instalação:
 Class 'Apiki\SEO\REST\Core' not found

**Comment by elvishp2006** [comment]
Você rodou o `composer install` para instalar as dependências do projeto? outra opção é já baixar o último release que lançamos, que já possui as dependências: https://github.com/Apiki/wordpress-seo-rest/releases/download/v1.2.3/wordpress-seo-rest.zip
